export const data = {
    'Москва': '/jsons/moscow.geojson',
    'Санкт-Петербург': '/jsons/saint-p.geojson',
    'Владимирская': '/jsons/vladimirskaya.geojson',
    'Калужская': '/jsons/kaluzhskaya.geojson',
    'Ивановская': '/jsons/ivanovskaya.geojson',
    'Брянская': '/jsons/bryansk.geojson',
    'Белгород': '/jsons/belgorod.geojson',
    'Костромская': '/jsons/kostroma.geojson',
    'Московская': '/jsons/moskovskaya.geojson',
    'Орловская': '/jsons/orlovskaya.geojson',
    'Тамбовская': '/jsons/tambovskaya.geojson',
    'Тверская': '/jsons/tverskaya.geojson',
    'Тульская': '/jsons/tulskaya.geojson',
    'Ярославская': '/jsons/yaroslavskaya.geojson',
    'Крым': '/jsons/krum.geojson',
    'Приморский': '/jsons/primorskiy.geojson',
    'Саха (Якутия)': '/jsons/saha.geojson',
    'Нижегородская': '/jsons/nizhegorodskaya.geojson',
    'Оренбургская': '/jsons/orenburgskaya.geojson',
    'Пермский': '/jsons/permskiy.geojson',
    'Татарстан': '/jsons/tatarstan.geojson',
    'Саратовская': '/jsons/saratovskaya.geojson',
    'Удмуртия': '/jsons/udm.geojson',
    'Алтайский': '/jsons/altay.geojson',
    'Иркутск': '/jsons/irkutsk.geojson',
    'Кемеровская область - Кузбасс': '/jsons/kemerovo.geojson',
    'Красноярский': '/jsons/krasnoyarsk.geojson',
    'Новосибирская': '/jsons/novosib.geojson',
    'Омская': '/jsons/omsk.geojson',
    'Хакасия': '/jsons/hackasiya.geojson',
    'Кабардино-Балкария': '/jsons/kab-b.geojson',
    'Дагестан': '/jsons/dagestan.geojson',
    'Ингушетия': '/jsons/ingush.geojson',
    'Вологодская': '/jsons/vologodsk.geojson',
    'Калининградская': '/jsons/kalin.geojson',
    'Ленинградская': '/jsons/lenin.geojson',
    'Мурманская': '/jsons/murm.geojson',
    'Ненецкий': '/jsons/nen.geojson',
    'Новгородская': '/jsons/novgor.geojson',
    'Псковская': '/jsons/pskov.geojson',
    'Курганская': '/jsons/kurg.geojson',
    'Свердловская': '/jsons/sverdl.geojson',
    'Тюменская': '/jsons/tumensk.geojson',
    'Ханты-Мансийский АО - Югра': '/jsons/hant.geojson',
    'Челябинская': '/jsons/chel.geojson',
    'Ямало-Ненецкий': '/jsons/yam-nen.geojson',
    'Волгоградская': '/jsons/volg.geojson',
    'Ростовская': '/jsons/rost.geojson'
}

export const token = 'pk.eyJ1IjoiaWxpYXZhcyIsImEiOiJjazcwdXU0dHkwMGViM21ta3VxaHB2YWNqIn0.yHEDUiatwp4dy4MM3ywnOQ';